//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA6WF.ServiceReferencePA6 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePA6.WebServicePA6Soap")]
    public interface WebServicePA6Soap {
        
        // CODEGEN: Generating message contract since element name GetEmployeesWhoWhereSick2004Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesWhoWhereSick2004", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Response GetEmployeesWhoWhereSick2004(PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesWhoWhereSick2004", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Response> GetEmployeesWhoWhereSick2004Async(PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Request request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesWithMostAbscenseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesWithMostAbscense", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseResponse GetEmployeesWithMostAbscense(PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesWithMostAbscense", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseResponse> GetEmployeesWithMostAbscenseAsync(PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesAndRelativesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesAndRelatives", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesResponse GetEmployeesAndRelatives(PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesAndRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesResponse> GetEmployeesAndRelativesAsync(PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMetaDataFromEmployeeTableResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetaDataFromEmployeeTable", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableResponse GetMetaDataFromEmployeeTable(PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetaDataFromEmployeeTable", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableResponse> GetMetaDataFromEmployeeTableAsync(PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequest request);
        
        // CODEGEN: Generating message contract since element name GetKeyConstraintsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeyConstraints", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetKeyConstraintsResponse GetKeyConstraints(PA6WF.ServiceReferencePA6.GetKeyConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeyConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetKeyConstraintsResponse> GetKeyConstraintsAsync(PA6WF.ServiceReferencePA6.GetKeyConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetIndexesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndexes", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetIndexesResponse GetIndexes(PA6WF.ServiceReferencePA6.GetIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetIndexesResponse> GetIndexesAsync(PA6WF.ServiceReferencePA6.GetIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name GetTableConstraintsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableConstraints", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetTableConstraintsResponse GetTableConstraints(PA6WF.ServiceReferencePA6.GetTableConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTableConstraintsResponse> GetTableConstraintsAsync(PA6WF.ServiceReferencePA6.GetTableConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetTablesMethodOneResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTablesMethodOne", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetTablesMethodOneResponse GetTablesMethodOne(PA6WF.ServiceReferencePA6.GetTablesMethodOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTablesMethodOne", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTablesMethodOneResponse> GetTablesMethodOneAsync(PA6WF.ServiceReferencePA6.GetTablesMethodOneRequest request);
        
        // CODEGEN: Generating message contract since element name GetTablesMethodTwoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTablesMethodTwo", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetTablesMethodTwoResponse GetTablesMethodTwo(PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTablesMethodTwo", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTablesMethodTwoResponse> GetTablesMethodTwoAsync(PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeeColumnsOneResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeColumnsOne", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneResponse GetEmployeeColumnsOne(PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeColumnsOne", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneResponse> GetEmployeeColumnsOneAsync(PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeeColumnsTwoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeColumnsTwo", ReplyAction="*")]
        PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoResponse GetEmployeeColumnsTwo(PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeColumnsTwo", ReplyAction="*")]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoResponse> GetEmployeeColumnsTwoAsync(PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesWhoWhereSick2004Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesWhoWhereSick2004", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004RequestBody Body;
        
        public GetEmployeesWhoWhereSick2004Request() {
        }
        
        public GetEmployeesWhoWhereSick2004Request(PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesWhoWhereSick2004RequestBody {
        
        public GetEmployeesWhoWhereSick2004RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesWhoWhereSick2004Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesWhoWhereSick2004Response", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004ResponseBody Body;
        
        public GetEmployeesWhoWhereSick2004Response() {
        }
        
        public GetEmployeesWhoWhereSick2004Response(PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesWhoWhereSick2004ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesWhoWhereSick2004Result;
        
        public GetEmployeesWhoWhereSick2004ResponseBody() {
        }
        
        public GetEmployeesWhoWhereSick2004ResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesWhoWhereSick2004Result) {
            this.GetEmployeesWhoWhereSick2004Result = GetEmployeesWhoWhereSick2004Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesWithMostAbscenseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesWithMostAbscense", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequestBody Body;
        
        public GetEmployeesWithMostAbscenseRequest() {
        }
        
        public GetEmployeesWithMostAbscenseRequest(PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesWithMostAbscenseRequestBody {
        
        public GetEmployeesWithMostAbscenseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesWithMostAbscenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesWithMostAbscenseResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseResponseBody Body;
        
        public GetEmployeesWithMostAbscenseResponse() {
        }
        
        public GetEmployeesWithMostAbscenseResponse(PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesWithMostAbscenseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesWithMostAbscenseResult;
        
        public GetEmployeesWithMostAbscenseResponseBody() {
        }
        
        public GetEmployeesWithMostAbscenseResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesWithMostAbscenseResult) {
            this.GetEmployeesWithMostAbscenseResult = GetEmployeesWithMostAbscenseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesAndRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesAndRelatives", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequestBody Body;
        
        public GetEmployeesAndRelativesRequest() {
        }
        
        public GetEmployeesAndRelativesRequest(PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesAndRelativesRequestBody {
        
        public GetEmployeesAndRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesAndRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesAndRelativesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesResponseBody Body;
        
        public GetEmployeesAndRelativesResponse() {
        }
        
        public GetEmployeesAndRelativesResponse(PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesAndRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesAndRelativesResult;
        
        public GetEmployeesAndRelativesResponseBody() {
        }
        
        public GetEmployeesAndRelativesResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesAndRelativesResult) {
            this.GetEmployeesAndRelativesResult = GetEmployeesAndRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetaDataFromEmployeeTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetaDataFromEmployeeTable", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequestBody Body;
        
        public GetMetaDataFromEmployeeTableRequest() {
        }
        
        public GetMetaDataFromEmployeeTableRequest(PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMetaDataFromEmployeeTableRequestBody {
        
        public GetMetaDataFromEmployeeTableRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetaDataFromEmployeeTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetaDataFromEmployeeTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableResponseBody Body;
        
        public GetMetaDataFromEmployeeTableResponse() {
        }
        
        public GetMetaDataFromEmployeeTableResponse(PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMetaDataFromEmployeeTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetMetaDataFromEmployeeTableResult;
        
        public GetMetaDataFromEmployeeTableResponseBody() {
        }
        
        public GetMetaDataFromEmployeeTableResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetMetaDataFromEmployeeTableResult) {
            this.GetMetaDataFromEmployeeTableResult = GetMetaDataFromEmployeeTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyConstraints", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetKeyConstraintsRequestBody Body;
        
        public GetKeyConstraintsRequest() {
        }
        
        public GetKeyConstraintsRequest(PA6WF.ServiceReferencePA6.GetKeyConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetKeyConstraintsRequestBody {
        
        public GetKeyConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetKeyConstraintsResponseBody Body;
        
        public GetKeyConstraintsResponse() {
        }
        
        public GetKeyConstraintsResponse(PA6WF.ServiceReferencePA6.GetKeyConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetKeyConstraintsResult;
        
        public GetKeyConstraintsResponseBody() {
        }
        
        public GetKeyConstraintsResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetKeyConstraintsResult) {
            this.GetKeyConstraintsResult = GetKeyConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndexes", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetIndexesRequestBody Body;
        
        public GetIndexesRequest() {
        }
        
        public GetIndexesRequest(PA6WF.ServiceReferencePA6.GetIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetIndexesRequestBody {
        
        public GetIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetIndexesResponseBody Body;
        
        public GetIndexesResponse() {
        }
        
        public GetIndexesResponse(PA6WF.ServiceReferencePA6.GetIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetIndexesResult;
        
        public GetIndexesResponseBody() {
        }
        
        public GetIndexesResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetIndexesResult) {
            this.GetIndexesResult = GetIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableConstraints", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetTableConstraintsRequestBody Body;
        
        public GetTableConstraintsRequest() {
        }
        
        public GetTableConstraintsRequest(PA6WF.ServiceReferencePA6.GetTableConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTableConstraintsRequestBody {
        
        public GetTableConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetTableConstraintsResponseBody Body;
        
        public GetTableConstraintsResponse() {
        }
        
        public GetTableConstraintsResponse(PA6WF.ServiceReferencePA6.GetTableConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTableConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTableConstraintsResult;
        
        public GetTableConstraintsResponseBody() {
        }
        
        public GetTableConstraintsResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTableConstraintsResult) {
            this.GetTableConstraintsResult = GetTableConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTablesMethodOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTablesMethodOne", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetTablesMethodOneRequestBody Body;
        
        public GetTablesMethodOneRequest() {
        }
        
        public GetTablesMethodOneRequest(PA6WF.ServiceReferencePA6.GetTablesMethodOneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTablesMethodOneRequestBody {
        
        public GetTablesMethodOneRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTablesMethodOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTablesMethodOneResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetTablesMethodOneResponseBody Body;
        
        public GetTablesMethodOneResponse() {
        }
        
        public GetTablesMethodOneResponse(PA6WF.ServiceReferencePA6.GetTablesMethodOneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTablesMethodOneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTablesMethodOneResult;
        
        public GetTablesMethodOneResponseBody() {
        }
        
        public GetTablesMethodOneResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTablesMethodOneResult) {
            this.GetTablesMethodOneResult = GetTablesMethodOneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTablesMethodTwoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTablesMethodTwo", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequestBody Body;
        
        public GetTablesMethodTwoRequest() {
        }
        
        public GetTablesMethodTwoRequest(PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTablesMethodTwoRequestBody {
        
        public GetTablesMethodTwoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTablesMethodTwoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTablesMethodTwoResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetTablesMethodTwoResponseBody Body;
        
        public GetTablesMethodTwoResponse() {
        }
        
        public GetTablesMethodTwoResponse(PA6WF.ServiceReferencePA6.GetTablesMethodTwoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTablesMethodTwoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTablesMethodTwoResult;
        
        public GetTablesMethodTwoResponseBody() {
        }
        
        public GetTablesMethodTwoResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTablesMethodTwoResult) {
            this.GetTablesMethodTwoResult = GetTablesMethodTwoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeColumnsOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeColumnsOne", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequestBody Body;
        
        public GetEmployeeColumnsOneRequest() {
        }
        
        public GetEmployeeColumnsOneRequest(PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeColumnsOneRequestBody {
        
        public GetEmployeeColumnsOneRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeColumnsOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeColumnsOneResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneResponseBody Body;
        
        public GetEmployeeColumnsOneResponse() {
        }
        
        public GetEmployeeColumnsOneResponse(PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeColumnsOneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeeColumnsOneResult;
        
        public GetEmployeeColumnsOneResponseBody() {
        }
        
        public GetEmployeeColumnsOneResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeeColumnsOneResult) {
            this.GetEmployeeColumnsOneResult = GetEmployeeColumnsOneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeColumnsTwoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeColumnsTwo", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequestBody Body;
        
        public GetEmployeeColumnsTwoRequest() {
        }
        
        public GetEmployeeColumnsTwoRequest(PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeColumnsTwoRequestBody {
        
        public GetEmployeeColumnsTwoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeColumnsTwoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeColumnsTwoResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoResponseBody Body;
        
        public GetEmployeeColumnsTwoResponse() {
        }
        
        public GetEmployeeColumnsTwoResponse(PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeColumnsTwoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeeColumnsTwoResult;
        
        public GetEmployeeColumnsTwoResponseBody() {
        }
        
        public GetEmployeeColumnsTwoResponseBody(System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeeColumnsTwoResult) {
            this.GetEmployeeColumnsTwoResult = GetEmployeeColumnsTwoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePA6SoapChannel : PA6WF.ServiceReferencePA6.WebServicePA6Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePA6SoapClient : System.ServiceModel.ClientBase<PA6WF.ServiceReferencePA6.WebServicePA6Soap>, PA6WF.ServiceReferencePA6.WebServicePA6Soap {
        
        public WebServicePA6SoapClient() {
        }
        
        public WebServicePA6SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePA6SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePA6SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePA6SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Response PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeesWhoWhereSick2004(PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Request request) {
            return base.Channel.GetEmployeesWhoWhereSick2004(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesWhoWhereSick2004() {
            PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Request inValue = new PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Request();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004RequestBody();
            PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Response retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeesWhoWhereSick2004(inValue);
            return retVal.Body.GetEmployeesWhoWhereSick2004Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Response> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeesWhoWhereSick2004Async(PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Request request) {
            return base.Channel.GetEmployeesWhoWhereSick2004Async(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Response> GetEmployeesWhoWhereSick2004Async() {
            PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Request inValue = new PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004Request();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeesWhoWhereSick2004RequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeesWhoWhereSick2004Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeesWithMostAbscense(PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequest request) {
            return base.Channel.GetEmployeesWithMostAbscense(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesWithMostAbscense() {
            PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequest inValue = new PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequestBody();
            PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeesWithMostAbscense(inValue);
            return retVal.Body.GetEmployeesWithMostAbscenseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeesWithMostAbscenseAsync(PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequest request) {
            return base.Channel.GetEmployeesWithMostAbscenseAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseResponse> GetEmployeesWithMostAbscenseAsync() {
            PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequest inValue = new PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeesWithMostAbscenseRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeesWithMostAbscenseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeesAndRelatives(PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequest request) {
            return base.Channel.GetEmployeesAndRelatives(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeesAndRelatives() {
            PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequest inValue = new PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequestBody();
            PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeesAndRelatives(inValue);
            return retVal.Body.GetEmployeesAndRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeesAndRelativesAsync(PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequest request) {
            return base.Channel.GetEmployeesAndRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesResponse> GetEmployeesAndRelativesAsync() {
            PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequest inValue = new PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeesAndRelativesRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeesAndRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetMetaDataFromEmployeeTable(PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequest request) {
            return base.Channel.GetMetaDataFromEmployeeTable(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetMetaDataFromEmployeeTable() {
            PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequest inValue = new PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequestBody();
            PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetMetaDataFromEmployeeTable(inValue);
            return retVal.Body.GetMetaDataFromEmployeeTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetMetaDataFromEmployeeTableAsync(PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequest request) {
            return base.Channel.GetMetaDataFromEmployeeTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableResponse> GetMetaDataFromEmployeeTableAsync() {
            PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequest inValue = new PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetMetaDataFromEmployeeTableRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetMetaDataFromEmployeeTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetKeyConstraintsResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetKeyConstraints(PA6WF.ServiceReferencePA6.GetKeyConstraintsRequest request) {
            return base.Channel.GetKeyConstraints(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetKeyConstraints() {
            PA6WF.ServiceReferencePA6.GetKeyConstraintsRequest inValue = new PA6WF.ServiceReferencePA6.GetKeyConstraintsRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetKeyConstraintsRequestBody();
            PA6WF.ServiceReferencePA6.GetKeyConstraintsResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetKeyConstraints(inValue);
            return retVal.Body.GetKeyConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetKeyConstraintsResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetKeyConstraintsAsync(PA6WF.ServiceReferencePA6.GetKeyConstraintsRequest request) {
            return base.Channel.GetKeyConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetKeyConstraintsResponse> GetKeyConstraintsAsync() {
            PA6WF.ServiceReferencePA6.GetKeyConstraintsRequest inValue = new PA6WF.ServiceReferencePA6.GetKeyConstraintsRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetKeyConstraintsRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetKeyConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetIndexesResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetIndexes(PA6WF.ServiceReferencePA6.GetIndexesRequest request) {
            return base.Channel.GetIndexes(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetIndexes() {
            PA6WF.ServiceReferencePA6.GetIndexesRequest inValue = new PA6WF.ServiceReferencePA6.GetIndexesRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetIndexesRequestBody();
            PA6WF.ServiceReferencePA6.GetIndexesResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetIndexes(inValue);
            return retVal.Body.GetIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetIndexesResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetIndexesAsync(PA6WF.ServiceReferencePA6.GetIndexesRequest request) {
            return base.Channel.GetIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetIndexesResponse> GetIndexesAsync() {
            PA6WF.ServiceReferencePA6.GetIndexesRequest inValue = new PA6WF.ServiceReferencePA6.GetIndexesRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetIndexesRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetTableConstraintsResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetTableConstraints(PA6WF.ServiceReferencePA6.GetTableConstraintsRequest request) {
            return base.Channel.GetTableConstraints(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTableConstraints() {
            PA6WF.ServiceReferencePA6.GetTableConstraintsRequest inValue = new PA6WF.ServiceReferencePA6.GetTableConstraintsRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetTableConstraintsRequestBody();
            PA6WF.ServiceReferencePA6.GetTableConstraintsResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetTableConstraints(inValue);
            return retVal.Body.GetTableConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTableConstraintsResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetTableConstraintsAsync(PA6WF.ServiceReferencePA6.GetTableConstraintsRequest request) {
            return base.Channel.GetTableConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTableConstraintsResponse> GetTableConstraintsAsync() {
            PA6WF.ServiceReferencePA6.GetTableConstraintsRequest inValue = new PA6WF.ServiceReferencePA6.GetTableConstraintsRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetTableConstraintsRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetTableConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetTablesMethodOneResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetTablesMethodOne(PA6WF.ServiceReferencePA6.GetTablesMethodOneRequest request) {
            return base.Channel.GetTablesMethodOne(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTablesMethodOne() {
            PA6WF.ServiceReferencePA6.GetTablesMethodOneRequest inValue = new PA6WF.ServiceReferencePA6.GetTablesMethodOneRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetTablesMethodOneRequestBody();
            PA6WF.ServiceReferencePA6.GetTablesMethodOneResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetTablesMethodOne(inValue);
            return retVal.Body.GetTablesMethodOneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTablesMethodOneResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetTablesMethodOneAsync(PA6WF.ServiceReferencePA6.GetTablesMethodOneRequest request) {
            return base.Channel.GetTablesMethodOneAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTablesMethodOneResponse> GetTablesMethodOneAsync() {
            PA6WF.ServiceReferencePA6.GetTablesMethodOneRequest inValue = new PA6WF.ServiceReferencePA6.GetTablesMethodOneRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetTablesMethodOneRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetTablesMethodOneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetTablesMethodTwoResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetTablesMethodTwo(PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequest request) {
            return base.Channel.GetTablesMethodTwo(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetTablesMethodTwo() {
            PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequest inValue = new PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequestBody();
            PA6WF.ServiceReferencePA6.GetTablesMethodTwoResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetTablesMethodTwo(inValue);
            return retVal.Body.GetTablesMethodTwoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTablesMethodTwoResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetTablesMethodTwoAsync(PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequest request) {
            return base.Channel.GetTablesMethodTwoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetTablesMethodTwoResponse> GetTablesMethodTwoAsync() {
            PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequest inValue = new PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetTablesMethodTwoRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetTablesMethodTwoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeeColumnsOne(PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequest request) {
            return base.Channel.GetEmployeeColumnsOne(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeeColumnsOne() {
            PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequest inValue = new PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequestBody();
            PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeeColumnsOne(inValue);
            return retVal.Body.GetEmployeeColumnsOneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeeColumnsOneAsync(PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequest request) {
            return base.Channel.GetEmployeeColumnsOneAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneResponse> GetEmployeeColumnsOneAsync() {
            PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequest inValue = new PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeeColumnsOneRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeeColumnsOneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoResponse PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeeColumnsTwo(PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequest request) {
            return base.Channel.GetEmployeeColumnsTwo(request);
        }
        
        public System.Collections.Generic.List<PA6WF.ServiceReferencePA6.ArrayOfString> GetEmployeeColumnsTwo() {
            PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequest inValue = new PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequestBody();
            PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoResponse retVal = ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeeColumnsTwo(inValue);
            return retVal.Body.GetEmployeeColumnsTwoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoResponse> PA6WF.ServiceReferencePA6.WebServicePA6Soap.GetEmployeeColumnsTwoAsync(PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequest request) {
            return base.Channel.GetEmployeeColumnsTwoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoResponse> GetEmployeeColumnsTwoAsync() {
            PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequest inValue = new PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequest();
            inValue.Body = new PA6WF.ServiceReferencePA6.GetEmployeeColumnsTwoRequestBody();
            return ((PA6WF.ServiceReferencePA6.WebServicePA6Soap)(this)).GetEmployeeColumnsTwoAsync(inValue);
        }
    }
}
