using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;


namespace PA4A
{
	
		//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "WebServicePA4Soap", Namespace = "http://tempuri.org/")]
	public partial class WebServicePA4 : System.Web.Services.Protocols.SoapHttpClientProtocol
	{

		private System.Threading.SendOrPostCallback GetCustomersOperationCompleted;

		private System.Threading.SendOrPostCallback GetAccountsOperationCompleted;

		/// <remarks/>
		public WebServicePA4()
		{
			this.Url = "http://localhost/PA4WS/WebServicePA4.asmx";
		}

		/// <remarks/>
		public event GetCustomersCompletedEventHandler GetCustomersCompleted;

		/// <remarks/>
		public event GetAccountsCompletedEventHandler GetAccountsCompleted;

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomers", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public Customer[] GetCustomers()
		{
			object[] results = this.Invoke("GetCustomers", new object[0]);
			return ((Customer[])(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("GetCustomers", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public Customer[] EndGetCustomers(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((Customer[])(results[0]));
		}

		/// <remarks/>
		public void GetCustomersAsync()
		{
			this.GetCustomersAsync(null);
		}

		/// <remarks/>
		public void GetCustomersAsync(object userState)
		{
			if ((this.GetCustomersOperationCompleted == null))
			{
				this.GetCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomersOperationCompleted);
			}
			this.InvokeAsync("GetCustomers", new object[0], this.GetCustomersOperationCompleted, userState);
		}

		private void OnGetCustomersOperationCompleted(object arg)
		{
			if ((this.GetCustomersCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccounts", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public Account[] GetAccounts()
		{
			object[] results = this.Invoke("GetAccounts", new object[0]);
			return ((Account[])(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginGetAccounts(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("GetAccounts", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public Account[] EndGetAccounts(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((Account[])(results[0]));
		}

		/// <remarks/>
		public void GetAccountsAsync()
		{
			this.GetAccountsAsync(null);
		}

		/// <remarks/>
		public void GetAccountsAsync(object userState)
		{
			if ((this.GetAccountsOperationCompleted == null))
			{
				this.GetAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountsOperationCompleted);
			}
			this.InvokeAsync("GetAccounts", new object[0], this.GetAccountsOperationCompleted, userState);
		}

		private void OnGetAccountsOperationCompleted(object arg)
		{
			if ((this.GetAccountsCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetAccountsCompleted(this, new GetAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		public new void CancelAsync(object userState)
		{
			base.CancelAsync(userState);
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
	public partial class Customer
	{

		private string sSNField;

		private string nameField;

		private string addressField;

		private string phoneNumberField;

		/// <remarks/>
		public string SSN
		{
			get
			{
				return this.sSNField;
			}
			set
			{
				this.sSNField = value;
			}
		}

		/// <remarks/>
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public string Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		/// <remarks/>
		public string PhoneNumber
		{
			get
			{
				return this.phoneNumberField;
			}
			set
			{
				this.phoneNumberField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
	public partial class Account
	{

		private string accountNumberField;

		private int balanceField;

		private string customerSSNField;

		/// <remarks/>
		public string AccountNumber
		{
			get
			{
				return this.accountNumberField;
			}
			set
			{
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		public int Balance
		{
			get
			{
				return this.balanceField;
			}
			set
			{
				this.balanceField = value;
			}
		}

		/// <remarks/>
		public string CustomerSSN
		{
			get
			{
				return this.customerSSNField;
			}
			set
			{
				this.customerSSNField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
	public delegate void GetCustomersCompletedEventHandler(object sender, GetCustomersCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// <remarks/>
		public Customer[] Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((Customer[])(this.results[0]));
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
	public delegate void GetAccountsCompletedEventHandler(object sender, GetAccountsCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GetAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal GetAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
				base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// <remarks/>
		public Account[] Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((Account[])(this.results[0]));
			}
		}
	}

}

