//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA4B.ServiceReferencePA4WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        private int BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSSNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerSSN {
            get {
                return this.CustomerSSNField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSSNField, value) != true)) {
                    this.CustomerSSNField = value;
                    this.RaisePropertyChanged("CustomerSSN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePA4WS.WebServicePA4Soap")]
    public interface WebServicePA4Soap {
        
        // CODEGEN: Generating message contract since element name GetCustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        PA4B.ServiceReferencePA4WS.GetCustomersResponse GetCustomers(PA4B.ServiceReferencePA4WS.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<PA4B.ServiceReferencePA4WS.GetCustomersResponse> GetCustomersAsync(PA4B.ServiceReferencePA4WS.GetCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name GetAccountsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccounts", ReplyAction="*")]
        PA4B.ServiceReferencePA4WS.GetAccountsResponse GetAccounts(PA4B.ServiceReferencePA4WS.GetAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<PA4B.ServiceReferencePA4WS.GetAccountsResponse> GetAccountsAsync(PA4B.ServiceReferencePA4WS.GetAccountsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomers", Namespace="http://tempuri.org/", Order=0)]
        public PA4B.ServiceReferencePA4WS.GetCustomersRequestBody Body;
        
        public GetCustomersRequest() {
        }
        
        public GetCustomersRequest(PA4B.ServiceReferencePA4WS.GetCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomersRequestBody {
        
        public GetCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA4B.ServiceReferencePA4WS.GetCustomersResponseBody Body;
        
        public GetCustomersResponse() {
        }
        
        public GetCustomersResponse(PA4B.ServiceReferencePA4WS.GetCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA4B.ServiceReferencePA4WS.Customer> GetCustomersResult;
        
        public GetCustomersResponseBody() {
        }
        
        public GetCustomersResponseBody(System.Collections.Generic.List<PA4B.ServiceReferencePA4WS.Customer> GetCustomersResult) {
            this.GetCustomersResult = GetCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccounts", Namespace="http://tempuri.org/", Order=0)]
        public PA4B.ServiceReferencePA4WS.GetAccountsRequestBody Body;
        
        public GetAccountsRequest() {
        }
        
        public GetAccountsRequest(PA4B.ServiceReferencePA4WS.GetAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAccountsRequestBody {
        
        public GetAccountsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PA4B.ServiceReferencePA4WS.GetAccountsResponseBody Body;
        
        public GetAccountsResponse() {
        }
        
        public GetAccountsResponse(PA4B.ServiceReferencePA4WS.GetAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PA4B.ServiceReferencePA4WS.Account> GetAccountsResult;
        
        public GetAccountsResponseBody() {
        }
        
        public GetAccountsResponseBody(System.Collections.Generic.List<PA4B.ServiceReferencePA4WS.Account> GetAccountsResult) {
            this.GetAccountsResult = GetAccountsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePA4SoapChannel : PA4B.ServiceReferencePA4WS.WebServicePA4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePA4SoapClient : System.ServiceModel.ClientBase<PA4B.ServiceReferencePA4WS.WebServicePA4Soap>, PA4B.ServiceReferencePA4WS.WebServicePA4Soap {
        
        public WebServicePA4SoapClient() {
        }
        
        public WebServicePA4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePA4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePA4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePA4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA4B.ServiceReferencePA4WS.GetCustomersResponse PA4B.ServiceReferencePA4WS.WebServicePA4Soap.GetCustomers(PA4B.ServiceReferencePA4WS.GetCustomersRequest request) {
            return base.Channel.GetCustomers(request);
        }
        
        public System.Collections.Generic.List<PA4B.ServiceReferencePA4WS.Customer> GetCustomers() {
            PA4B.ServiceReferencePA4WS.GetCustomersRequest inValue = new PA4B.ServiceReferencePA4WS.GetCustomersRequest();
            inValue.Body = new PA4B.ServiceReferencePA4WS.GetCustomersRequestBody();
            PA4B.ServiceReferencePA4WS.GetCustomersResponse retVal = ((PA4B.ServiceReferencePA4WS.WebServicePA4Soap)(this)).GetCustomers(inValue);
            return retVal.Body.GetCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA4B.ServiceReferencePA4WS.GetCustomersResponse> PA4B.ServiceReferencePA4WS.WebServicePA4Soap.GetCustomersAsync(PA4B.ServiceReferencePA4WS.GetCustomersRequest request) {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA4B.ServiceReferencePA4WS.GetCustomersResponse> GetCustomersAsync() {
            PA4B.ServiceReferencePA4WS.GetCustomersRequest inValue = new PA4B.ServiceReferencePA4WS.GetCustomersRequest();
            inValue.Body = new PA4B.ServiceReferencePA4WS.GetCustomersRequestBody();
            return ((PA4B.ServiceReferencePA4WS.WebServicePA4Soap)(this)).GetCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PA4B.ServiceReferencePA4WS.GetAccountsResponse PA4B.ServiceReferencePA4WS.WebServicePA4Soap.GetAccounts(PA4B.ServiceReferencePA4WS.GetAccountsRequest request) {
            return base.Channel.GetAccounts(request);
        }
        
        public System.Collections.Generic.List<PA4B.ServiceReferencePA4WS.Account> GetAccounts() {
            PA4B.ServiceReferencePA4WS.GetAccountsRequest inValue = new PA4B.ServiceReferencePA4WS.GetAccountsRequest();
            inValue.Body = new PA4B.ServiceReferencePA4WS.GetAccountsRequestBody();
            PA4B.ServiceReferencePA4WS.GetAccountsResponse retVal = ((PA4B.ServiceReferencePA4WS.WebServicePA4Soap)(this)).GetAccounts(inValue);
            return retVal.Body.GetAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PA4B.ServiceReferencePA4WS.GetAccountsResponse> PA4B.ServiceReferencePA4WS.WebServicePA4Soap.GetAccountsAsync(PA4B.ServiceReferencePA4WS.GetAccountsRequest request) {
            return base.Channel.GetAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PA4B.ServiceReferencePA4WS.GetAccountsResponse> GetAccountsAsync() {
            PA4B.ServiceReferencePA4WS.GetAccountsRequest inValue = new PA4B.ServiceReferencePA4WS.GetAccountsRequest();
            inValue.Body = new PA4B.ServiceReferencePA4WS.GetAccountsRequestBody();
            return ((PA4B.ServiceReferencePA4WS.WebServicePA4Soap)(this)).GetAccountsAsync(inValue);
        }
    }
}
